name: form_demo_web
description: data base programm

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mysql1: ^0.20.0
  provider: ^6.0.4
  path_provider: ^2.0.11
  shared_preferences: ^2.2.1
  file_picker: ^5.5.0
  desktop_window: ^0.4.0
  math_expressions: ^2.4.0
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  build_runner: ^2.3.2
#  drift_dev: ^2.3.2


flutter:

  uses-material-design: true
  assets:
    - images/



  #
